<?php

/**
 * @file
 * Contains liberty_claims.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\GeneratedLink;
use Drupal\views\ViewExecutable;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;

/**
 * Lib core views pre render children hook_views_pre_render .
 *
 * @param \Drupal\views\ViewExecutable $view
 *   The view object.
 */
function lib_core_views_pre_render(ViewExecutable $view):void {
  if ($view->storage->id() == 'payment_methods') {
    $view->element['#attached']['library'][] = 'lib_core/payment-methods';
  }
}

/**
 * Lib core form alter childen hook_form_alter .
 *
 * @param array<string, mixed> $form
 *   The form array.
 */
function lib_core_form_alter(array &$form, FormStateInterface $form_state, string $form_id):void {

  if ($form_id == 'webform_submission_solicitud_add_form' || $form_id == 'webform_submission_solicitud_paragraph_156_add_form') {

    $form['elements']['descripcion_de_auto']['#attributes']['class'][] = 'msg-description';
    $form['elements']['descripcion_de_cumplimiento']['#attributes']['class'][] = 'msg-description';
    $form['elements']['descripcion_de_salud']['#attributes']['class'][] = 'msg-description';
    $form['elements']['descripcion_de_soat']['#attributes']['class'][] = 'msg-description';
    $form['elements']['descripcion_de_vida']['#attributes']['class'][] = 'msg-description';

  }

  if ($form_id == 'views_exposed_form' && isset($form['field_product_type_target_id'])) {
    $form['field_product_type_target_id']['#attributes'] = [
      'placeholder' => 'Select a product to know its payment method',
    ];
    $form['actions']['submit']['#name'] = 'button-filter-product-type';
  }

  if ($form_id == 'views_exposed_form' && isset($form['#id']) && $form['#id'] == 'views-exposed-form-clauses-documents-page-2') {
    $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
    $form['title']['#attributes']['placeholder'] = 'Encuentra la documentación que necesitas para tus procesos con Liberty';
    $form['title']['#size'] = 60;
    $form['#action'] = "/zona-de-cliente/clausulas-y-documentos";
  }
  if ($form_id == 'views_exposed_form' && isset($form['#id']) && $form['#id'] == 'views-exposed-form-faqs-page-1') {
    $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
    $form['title']['#attributes']['placeholder'] = '¿En qué podemos ayudarte?';
    $form['title']['#size'] = 60;
    $form['#action'] = "/zona-de-cliente/preguntas-frecuentes";
  }
}

/**
 * Lib core views pre view children hook_views_pre_view.
 *
 * @param \Drupal\views\ViewExecutable $view
 *   The view object.
 * @param string $display_id
 *   The display ID.
 * @param string[] $args
 *   Array with custom arguments.
 */
function lib_core_views_pre_view(ViewExecutable $view, string $display_id, array &$args): void {
  $account = \Drupal::currentUser();
  if ($view->id() == 'my_special_view' && $account->hasPermission('my special permission') && $display_id == 'public_display') {
    $args[0] = 'custom value';
  }

  if ($view->id() == 'faqs' && $display_id == 'block_3') {
    $node = \Drupal::routeMatch()->getParameter('node');
    $category = $node->get('field_category_faq')->getValue();
    if (isset($category[0]['target_id'])) {
      $args[0] = $category[0]['target_id'];
    }
  }

  if (($view->id() == 'clauses_documents' && $display_id === 'page_1') || ($view->id() == 'faqs' && $display_id === 'page_2')) {
    $category = \Drupal::request()->query->get('category');
    if (!empty($category) && is_numeric($category) && $category > 0) {
      $args[0] = $category;
    }
  }
}

/**
 * Lib core theme childen hook_theme.
 *
 * @param object[] $existing
 *   Examine existing implementations.
 *
 * @return array<string, mixed>
 *   an array of theme implementations
 */
function lib_core_theme(array $existing, string $type, string $theme, string $path) : array {
  return [
    'tabs_assistances' => [
      'variables' => [
        'ramos' => NULL,
        'products' => NULL,
        'block_contact' => NULL,
      ],
      'template' => 'tabs_assistances',
    ],
    'tabs_documents_required' => [
      'variables' => [
        'ramos' => NULL,
        'products' => NULL,
        'block_contact' => NULL,
      ],
      'template' => 'tabs_documents_required',
    ],
  ];
}

/**
 * Lib core preprocess file link children hook_preprocess_file_link().
 *
 * @param array<string, mixed> $variables
 *   The variables object links.
 */
function lib_core_preprocess_file_link(&$variables) : void {
  if (isset($variables['link']) && $variables['link'] instanceof GeneratedLink) {
    $doc = new DOMDocument();
    $doc->loadHTML(mb_convert_encoding($variables['link']->getGeneratedLink(), 'HTML-ENTITIES', 'UTF-8'));
    $node = $doc->getElementsByTagName('a')[0];
    $node->setAttribute('target', '_blank');
    $html = $doc->saveHTML();
    if (is_string($html)) {
      $variables['link']->setGeneratedLink($html);
    }
  }
}

/**
 * Lib core node vie alter children hook_ENTITY_TYPE_view_alter.
 *
 * @param array<string, mixed> $build
 *   Representing the entity content.
 */
function lib_core_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display):void {

  if ($entity->bundle() == 'campaign') {
    // @todo Agregar validacion a view mode full
    $build['#cache']['max-age'] = 0;
    \Drupal::service('page_cache_kill_switch')->trigger();
  }
}

/**
 * Lib core cron children hook_cron.
 */
function lib_core_cron():void {
  $date = strtotime("-1 day");
  $database = \Drupal::database();
  $database->query("delete from sessions where timestamp < '" . $date . "';");

  $file_system = \Drupal::service('file_system');
  $files = \Drupal::entityTypeManager()
    ->getStorage('file')
    ->getQuery()
    ->condition('uri', '%pqr%', 'LIKE')
    ->accessCheck(FALSE)
    ->execute();
  $storage_handler = \Drupal::entityTypeManager()->getStorage("file");

  foreach ($files as $file) {
    $locale_directory = $storage_handler->load($file)->get('uri')->getValue()[0]['value'];
    $directory = explode('/', $locale_directory);
    $uri = $directory[0] . '//' . $directory[2] . '/';
    if (is_dir($uri)) {
      if (!$file_system->scanDirectory($uri, '/.*/')) {
        $file_system->rmdir($uri);
      }
    }

  }
  $entities = $storage_handler->loadMultiple($files);
  $storage_handler->delete($entities);

}

/**
 * Create submission webform.
 *
 * @param array<string, mixed> $webform_data
 *   Get data from submission webform.
 */
function lib_core_createsubmit(array $webform_data):void {

  // Convert to webform values format.
  $values = $webform_data;

  $values['webform_id'] = $webform_data['webform_id'];
  $values['entity_type'] = NULL;
  $values['entity_id'] = NULL;

  // Don't submit webform ID.
  unset($values['data']['webform_id']);
  unset($values['data']['back']);
  unset($values['data']['next']);
  unset($values['data']['form_build_id']);
  unset($values['data']['form_token']);
  unset($values['data']['form_token']);
  unset($values['data']['form_id']);
  unset($values['data']['debugEmail']);
  unset($values['data']['debug']);
  unset($values['data']['retURL']);
  unset($values['data']['orgid']);

  $webform = Webform::load($values['webform_id']);

  $submission = WebformSubmission::create([
    'webform_id' => $webform->id(),
  ]);

  foreach ($values['data'] as $field_key => $field_value) {
    $submission->setElementData(strtolower($field_key), $field_value);
  }
  $submission->save();

}
